<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>publications | You R. Name</title>
    <meta name="author" content="You R. Name" />
    <meta name="description" content="publications by categories in reversed chronological order. generated by jekyll-scholar." />
    <meta name="keywords" content="jekyll, jekyll-theme, academic-website, portfolio-website" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css" integrity="sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css" integrity="sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.1/css/academicons.min.css" integrity="sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg=" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jwarby/jekyll-pygments-themes@master/github.css" media="none" id="highlight_theme_light" />
    <link rel="shortcut icon" href="data:image/svg+xml,
										<svg
											xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22>
											<text y=%22.9em%22 font-size=%2290%22>⚛️</text>
										</svg>">
    <link rel="stylesheet" href="/assets/css/main.css">
    <link rel="canonical" href="https://mmvalinezhad.github.io/publications/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jwarby/jekyll-pygments-themes@master/native.css" media="none" id="highlight_theme_dark" />
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/dark_mode.js"></script>
  </head>
  <body class="fixed-top-nav ">
    <header>
      <nav id="navbar" class="navbar navbar-light navbar-expand-sm fixed-top">
        <div class="container">
          <a class="navbar-brand title font-weight-lighter" href="https://mmvalinezhad.github.io/">
            <span class="font-weight-bold">You</span> R. Name </a>
          <button class="navbar-toggler collapsed ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar top-bar"></span>
            <span class="icon-bar middle-bar"></span>
            <span class="icon-bar bottom-bar"></span>
          </button>
          <div class="collapse navbar-collapse text-right" id="navbarNav">
            <ul class="navbar-nav ml-auto flex-nowrap">
              <li class="nav-item ">
                <a class="nav-link" href="/">about</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="/blog/">blog</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="/projects/">projects</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/publications/">publications <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="/teaching/">teaching</a>
              </li>
              <li class="nav-item dropdown ">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">submenus</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/publications/">publications</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/projects/">projects</a>
                </div>
              </li>
              <div class="toggle-container">
                <a id="light-toggle">
                  <i class="fas fa-moon"></i>
                  <i class="fas fa-sun"></i>
                </a>
              </div>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container mt-5">
      <div class="post">
        <header class="post-header">
          <h1 class="post-title">Publications</h1>
          <p class="post-description">publications by categories in reversed chronological order. generated by jekyll-scholar.</p>
        </header>
        <article>
          <div class="publications">
            <h2 class="year">2022</h2>
            <ol class="bibliography">
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr">
                    <abbr class="badge">AEUE</abbr>
                  </div>
                  <div id="PhysRev.47.777" class="col-sm-8">
                    <div class="title">A Nano-Power Sub-Bandgap Voltage and Current Reference Topology with No Amplifier</div>
                    <div class="author">
                      <em>Aminzadeh, H.</em>and Valinezhad, M.M.</a>
                    </div>
                    <div class="periodical">
                      <em>AEUE</em> May 2022
                    </div>
                    <div class="links">
                      <a class="abstract btn btn-sm z-depth-0" role="button">Abs</a>
                      <a href="https://www.sciencedirect.com/science/article/abs/pii/S1434841122000711" class="btn btn-sm z-depth-0" role="button" target="_blank" rel="noopener noreferrer">HTML</a>
                    </div>
                    <div class="abstract hidden">
                      <p>A sub-bandgap current and voltage reference operating at ultra-low quiescent current is proposed for energy harvesting and battery-operated systems. Using a single bipolar junction transistor (BJT) and no operational amplifier (opamp), the current reference is generated from proportional-to-absolute-temperature (PTAT) and complementary-to-absolute-temperature (CTAT) voltages combined in a simple three-branch self-biased structure, while the voltage reference is derived by driving the current reference to a temperature-insensitive resistor. The line sensitivity (LS) is enhanced by incorporating cascode devices into the original configuration. Designed in a 0.18-µm standard CMOS process, the proposed architecture occupies an active area of 609 µm × 755 µm with around 47 nA current consumption regardless of temperature. The generated current and voltage references are 6.7 nA and 180 mV, and their temperature coefficients (TC) are 32.76 ppm/°C and 34.80 ppm/°C across the temperature range from −40 to 120 °C, respectively. The minimum supply voltage is 1.1 V, and the line sensitivity of the voltage and current reference are 0.031%/V and 0.03%/V, respectively, over the supply voltage range of 1.1–1.8 V.</p>
                    </div>
                  </div>
                </div>
              </li>
            </ol>
            <h2 class="year">2020</h2>
            <ol class="bibliography">
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr">
                    <abbr class="badge">Circuit World</abbr>
                  </div>
                  <div id="PhysRev.47.777" class="col-sm-8">
                    <div class="title">Hybrid Cascode Compensation with Q-factor Control Module for Three-Stage OTAs Driving Ultra-Large Load Capacitors</div>
                    <div class="author">
                      Aminzadeh, H. and <em>Valinezhad, M.M.</em></a>
                    </div>
                    <div class="periodical">
                      <em>Circuit World</em> Aug 2020
                    </div>
                    <div class="links">
                      <a class="abstract btn btn-sm z-depth-0" role="button">Abs</a>
                      <a href="https://www.emerald.com/insight/content/doi/10.1108/CW-03-2020-0036/full/html" class="btn btn-sm z-depth-0" role="button" target="_blank" rel="noopener noreferrer">HTML</a>
                    </div>
                    <div class="abstract hidden">
                      <p>The purpose of this study is to discuss the effect of hybrid cascode compensation with quality factor (Q-factor) control module for the three-stage amplifiers driving ultra-large load capacitors. Compared to the present frequency compensation solutions, it extends the amplifier bandwidth by establishing an extra AC feedback pathway besides the primary pathway through the Miller capacitor, increasing the loop gain at the gain–bandwidth product (GBW) frequency by pushing to the higher frequencies the nondominant poles.</p>
                    </div>
                  </div>
                </div>
              </li>
            </ol>
            <ol class="bibliography">
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr">
                    <abbr class="badge">Microelectronics J</abbr>
                  </div>
                  <div id="PhysRev.47.777" class="col-sm-8">
                    <div class="title">0.7-V supply, 21-nW All–MOS Voltage Reference Using a MOS-Only Current-Driven Reference Core in Digital CMOS</div>
                    <div class="author">
                      Aminzadeh, H.and <em>Valinezhad, M.M.</em></a>
                    </div>
                    <div class="periodical">
                      <em>Microelectronics Journal</em> Aug 2020
                    </div>
                    <div class="links">
                      <a class="abstract btn btn-sm z-depth-0" role="button">Abs</a>
                      <a href="https://www.sciencedirect.com/science/article/abs/pii/S0026269219310821" class="btn btn-sm z-depth-0" role="button" target="_blank" rel="noopener noreferrer">HTML</a>
                    </div>
                    <div class="abstract hidden">
                      <p>A nano-power all-MOS voltage reference circuit is proposed without any integrated resistor or bipolar transistor to generate multiple voltage sources in inexpensive digital CMOS technologies. The design is based on a current-driven voltage reference core made by standard nMOS transistors only, and can be powered up by a flexible biasing current with no consideration on its temperature characteristics. The sensitive core is shielded from the unregulated voltage supply via a voltage follower MOS transistor, whose gate terminal is driven by a supply-insensitive voltage source coming from the internal biasing configuration. The additional voltage reference is generated using the type of the biasing current made by the main voltage reference loaded by a transistor. A MOS-only implementation of the proposed reference employs MOS devices instead of passive resistors and linear capacitors. A prototype of the proposed solution consumes 30 ​nA with an area of 0.01 ​mm2 in 0.18-μm CMOS process, producing a main voltage reference of 147 ​mV while operating at the supply voltage down to 0.7 ​V. Simulation results demonstrate an average temperature coefficient (TC) of 66.38 ​ppm/°C for a temperature range of −40 to 120 ​°C. The line sensitivity is about 0.031%/V for the line voltages above 1.3 ​V. The mean power supply rejection ratio (PSRR) is −90 dB and −64.4 ​dB ​at 10 ​Hz and 1 ​MHz, respectively, when the voltage supply is set to 1.8 ​V and an equivalent MOS capacitor of 5 ​pF is used at the output. The 1% start-up settling time is 240 μs for a 1.0 ​V voltage supply step, and can be reduced by increasing the supply voltage magnitude.</p>
                    </div>
                  </div>
                </div>
              </li>
            </ol>

			<ol class="bibliography">
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr">
                    <abbr class="badge">IJCTA</abbr>
                  </div>
                  <div id="PhysRev.47.777" class="col-sm-8">
                    <div class="title">Global Impedance Attenuation Network for Multistage OTAs Driving a Broad Range of Load Capacitor</div>
                    <div class="author">
                      Aminzadeh, H., <em>Valinezhad, M.M.</em> and Grasso, A. D.</a>
                    </div>
                    <div class="periodical">
                      <em>International Journal of Circuit Theory and Applications</em> Jan 2020
                    </div>
                    <div class="links">
                      <a class="abstract btn btn-sm z-depth-0" role="button">Abs</a>
                      <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/cta.2723" class="btn btn-sm z-depth-0" role="button" target="_blank" rel="noopener noreferrer">HTML</a>
                    </div>
                    <div class="abstract hidden">
                      <p>Advanced multistage amplifiers suffer from load-dependent stability issues, which limit the load capacitor range they can drive. In this work, the concept of global impedance attenuation (GIA) network is introduced to improve an amplifier's stability in the presence of significant load capacitor variations. Composed of multiple parallel resistor-capacitor (RC) branches, the equivalent high-frequency output impedance of gain stages is shaped by the GIA network such that a desired frequency spectrum is obtained over a wide range of load capacitor. The parasitic poles at the output of the gain stages are nullified by the proposed network, thereby simplifying the amplifier's transfer function and reducing the minimum load capacitor it can drive. The idea is applied to design a three-stage operational transconductance amplifier (OTA) with cascode global impedance attenuation (CGIA). Small-signal analysis shows that the OTA is stable regardless of the load capacitor, and it can drive very small to ultra-large load capacitors. This feature is verified by the post-layout simulations of a CGIA amplifier in 0.18-μm complementary metal-oxide semiconductor (CMOS) process. The core occupies a die area of 0.0053 mm2 while consuming a static current of 10.97 μA from 1.8-V voltage supply. The unity-feedback configuration is unconditionally stable for any load capacitor higher than 10 pF. To the best of our knowledge, this corresponds to the widest range of load capacitance reported for prior-art three-stage amplifiers.</p>
                    </div>
                  </div>
                </div>
              </li>
            </ol>

            <h2 class="year">1935</h2>
            <ol class="bibliography">
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr">
                    <abbr class="badge">PhysRev</abbr>
                  </div>
                  <div id="PhysRev.47.777" class="col-sm-8">
                    <div class="title">Can Quantum-Mechanical Description of Physical Reality Be Considered Complete?</div>
                    <div class="author">
                      <em>Einstein, A.</em>,  <a href="https://en.wikipedia.org/wiki/Boris_Podolsky" target="_blank" rel="noopener noreferrer">Podolsky, B.</a>, and <a href="https://en.wikipedia.org/wiki/Nathan_Rosen" target="_blank" rel="noopener noreferrer">Rosen, N.</a>
                    </div>
                    <div class="periodical">
                      <em>Phys. Rev.,</em> May 1935
                    </div>
                    <div class="links">
                      <a class="abstract btn btn-sm z-depth-0" role="button">Abs</a>
                      <a href="https://journals.aps.org/pr/abstract/10.1103/PhysRev.47.777" class="btn btn-sm z-depth-0" role="button" target="_blank" rel="noopener noreferrer">HTML</a>
                      <a href="/assets/pdf/example_pdf.pdf" class="btn btn-sm z-depth-0" role="button">PDF</a>
                    </div>
                    <div class="abstract hidden">
                      <p>In a complete theory there is an element corresponding to each element of reality. A sufficient condition for the reality of a physical quantity is the possibility of predicting it with certainty, without disturbing the system. In quantum mechanics in the case of two physical quantities described by non-commuting operators, the knowledge of one precludes the knowledge of the other. Then either (1) the description of reality given by the wave function in quantum mechanics is not complete or (2) these two quantities cannot have simultaneous reality. Consideration of the problem of making predictions concerning a system on the basis of measurements made on another system that had previously interacted with it leads to the result that if (1) is false then (2) is also false. One is thus led to conclude that the description of reality as given by a wave function is not complete.</p>
                    </div>
                  </div>
                </div>
              </li>
            </ol>
            <h2 class="year">1905</h2>
            <ol class="bibliography">
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr"></div>
                  <div id="einstein1905molekularkinetischen" class="col-sm-8">
                    <div class="title">Über die von der molekularkinetischen Theorie der Wärme geforderte Bewegung von in ruhenden Flüssigkeiten suspendierten Teilchen</div>
                    <div class="author">
                      <em>Einstein, A.</em>
                    </div>
                    <div class="periodical">
                      <em>Annalen der physik,</em> May 1905
                    </div>
                    <div class="links"></div>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr">
                    <abbr class="badge">Ann. Phys.</abbr>
                  </div>
                  <div id="einstein1905movement" class="col-sm-8">
                    <div class="title">Un the movement of small particles suspended in statiunary liquids required by the molecular-kinetic theory 0f heat</div>
                    <div class="author">
                      <em>Einstein, A.</em>
                    </div>
                    <div class="periodical">
                      <em>Ann. Phys.,</em> May 1905
                    </div>
                    <div class="links"></div>
                  </div>
                </div>
              </li>
              <li>
                <div class="row">
                  <div class="col-sm-2 abbr"></div>
                  <div id="einstein1905electrodynamics" class="col-sm-8">
                    <div class="title">On the electrodynamics of moving bodies</div>
                    <div class="author">
                      <em>Einstein, A.</em>
                    </div>
                    <div class="periodical">
                      <em></em> May 1905
                    </div>
                    <div class="links"></div>
                  </div>
                </div>
              </li>
            </ol>
          </div>
        </article>
      </div>
    </div>
    <footer class="fixed-bottom">
      <div class="container mt-0"> © Copyright 2022 You R. Name. Powered by <a href="https://jekyllrb.com/" target="_blank" rel="noopener noreferrer">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio" target="_blank" rel="noopener noreferrer">al-folio</a> theme. Hosted by <a href="https://pages.github.com/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>. Photos from <a href="https://unsplash.com" target="_blank" rel="noopener noreferrer">Unsplash</a>. </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.2/dist/umd/popper.min.js" integrity="sha256-l/1pMF/+J4TThfgARS6KwWrk/egwuVvhRzfLAMQ6Ds4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js" integrity="sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script defer src="/assets/js/masonry.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.min.js" integrity="sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM=" crossorigin="anonymous"></script>
    <script src="/assets/js/zoom.js"></script>
    <script src="/assets/js/common.js"></script>
    <script type="text/javascript">
      window.MathJax = {
        tex: {
          tags: "ams"
        }
      };
    </script>
    <script defer type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3.2.0/es5/tex-mml-chtml.js"></script>
    <script defer src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  </body>
</html>
